development:
  adapter: mysql2
  encoding: utf8
  database: cpwa_db
  pool: 5
  username: root
  password:


test:
  adapter: mysql2
  encoding: utf8
  database: cpwa_db
  pool: 5
  username: root
  password:


production:
  adapter: mysql2
  encoding: utf8
  database: cpwa_db
  pool: 5
  username: root
  password: